version: '3.9'
services:
  aut_leaderboard_web: 
    container_name: aut_leaderboard_web
    image: aut_leaderboard_web
    build: ./

  aut_leaderboard_nginx:
    container_name: aut_leaderboard_nginx
    image: aut_leaderboard_nginx
    build: ./nginx
    ports:
      - 4001:9080
