version: '3.9'
services:
  aut_leaderboard_dev: 
    container_name: aut_leaderboard_dev
    image: aut_leaderboard_dev
    build: ./

  aut_leaderboard_nginx_dev:
    container_name: aut_leaderboard_nginx_dev
    image: aut_leaderboard_nginx_dev
    build: ./nginx/dev
    ports:
      - 4001:9080
